// Code generated by scripts/regen-embedded.sh (из релиза форка hoaxisr/amnezia-box); DO NOT EDIT.
package installer

const RequiredVersion = "1.15.0-alpha.10-awgm.31"

// RequiredTags — теги сборки pinned-бинаря (строка `Tags:` из `sing-box version`),
// сняты с mipsel-ассета. Гейт-значимые теги (with_naive_outbound) одинаковы
// для всех трёх архитектур; служебные (with_low_memory, with_musl) могут
// отличаться — это только отображение в Status.Features.
// Обновляется regen-embedded.sh под qemu-user; без qemu — руками при бампе.
var RequiredTags = []string{"with_quic", "with_wireguard", "with_utls", "with_acme", "with_clash_api", "with_v2ray_api", "with_naive_outbound", "with_cloudflared", "badlinkname", "tfogo_checklinkname0", "with_musl", "with_awg", "with_low_memory", "with_trusttunnel"}

var EmbeddedBinaries = map[string]BinarySpec{
	"mipsel-3.4":   {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/singbox/1.15.0-alpha.10-awgm.31/singbox-1.15.0-alpha.10-awgm.31-mipsel-3.4", SHA256: "4c78a0b6a750feff53952a29515103d288322bd2867ed662fd28dd45a7936bc7", Size: 70365628},
	"mips-3.4":     {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/singbox/1.15.0-alpha.10-awgm.31/singbox-1.15.0-alpha.10-awgm.31-mips-3.4", SHA256: "55aca6d4ac543d34d3273911c534821e88b1ce638f3ee3f6aaa3ea01d597db33", Size: 52166813},
	"aarch64-3.10": {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/singbox/1.15.0-alpha.10-awgm.31/singbox-1.15.0-alpha.10-awgm.31-aarch64-3.10", SHA256: "0597dcbc2e2117fb3e96c0d9a103eb3c7207c07f80312e475608a24e20a54c3e", Size: 57341832},
}
